# Generated by Microsoft365DSC from https://export.microsoft365dsc.com on 21/1/2026, 2:20:36 pm
# Visit https://microsoft365dsc.com for more information

# Getting client credential
$Credential = Get-Credential

# Exporting resources using credentials
Export-M365DSCConfiguration -Components @("AADAccessReviewDefinition", "AADAccessReviewPolicy", "AADActivityBasedTimeoutPolicy", "AADAdminConsentRequestPolicy", "AADAdministrativeUnit", "AADAgreement", "AADAppManagementPolicy", "AADAttributeSet", "AADAuthenticationContextClassReference", "AADAuthenticationFlowPolicy", "AADAuthenticationMethodPolicy", "AADAuthenticationMethodPolicyAuthenticator", "AADAuthenticationMethodPolicyEmail", "AADAuthenticationMethodPolicyExternal", "AADAuthenticationMethodPolicyFido2", "AADAuthenticationMethodPolicyHardware", "AADAuthenticationMethodPolicyQRCodeImage", "AADAuthenticationMethodPolicySms", "AADAuthenticationMethodPolicySoftware", "AADAuthenticationMethodPolicyTemporary", "AADAuthenticationMethodPolicyVoice") -Credential $Credential